### ISSUE TITLE
[Token]: Uni

### ISSUE THREAD

**Issue by specialjp** [scroll-tech/token-list#31]
### scrollEnvironment

alpha

### chainId

534353

### address

0x99AC7BaB8682AE7d9B5ffCC2DD0d0101f5341B1F

### name

Uniswap

### symbol

UNI

### decimals

18

### logoURI

https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png

**Comment by yqrashawn** [comment]
Close in favor of new token list
