### ISSUE TITLE
[Token]: DAI

### ISSUE THREAD

**Issue by Zhiyong-Hu** [scroll-tech/token-list#33]
### scrollEnvironment

alpha

### chainId

534353

### address

0xe34E71bEE0Bbb08B4dDb8064A5A368Bfaa1E6eFc

### name

Dai Stablecoin

### symbol

DAI

### decimals

18

### logoURI

https://s2.coinmarketcap.com/static/img/coins/64x64/4943.png

**Comment by yqrashawn** [comment]
Close in favor of new token list
