### ISSUE TITLE
[Token]: AORAP

### ISSUE THREAD

**Issue by Dalgerok** [scroll-tech/token-list#35]
### scrollEnvironment

alpha

### chainId

534353

### address

0x98dF7E2A9aB760177049217CC77aC9513475A46e

### name

Andrii Orap coin

### symbol

AORAP

### decimals

18

### logoURI

https://upanh.tv/image/in5F1H

**Comment by Dalgerok** [comment]
Hi, I would like to still ask you to consider my candidacy.

Updated CV (added my crypto experience): https://drive.google.com/file/d/12slo86CSW1db6Ud7ZIMNcGh3TCnoWU0n/view?usp=sharing

**Comment by yqrashawn** [comment]
Close in favor of new token list
