### ISSUE TITLE
[Token]: zkFrens

### ISSUE THREAD

**Issue by lovinboi** [scroll-tech/token-list#37]
### scrollEnvironment

alpha

### chainId

534353

### address

0x0b5E46C351C347552Fe623e589390a0224183dA5

### name

zKfrens

### symbol

ZKF

### decimals

18

### logoURI

/ipfs/QmXwfxsKR31jWz4e9cj9wZEx4iBJmFf3N9XUUDdF2qj4CE?_gl=1*ofrjzj*_ga*NmMxNTU2NjAtYzEyZi00MjY5LThlOWItZTRjYjg4ZDExNzM3*_ga_5RMPXG14TE*MTY4MDM0MzMzOS4yLjEuMTY4MDM0MzM3NS4yNC4wLjA.

**Comment by yqrashawn** [comment]
Close in favor of new token list
