### ISSUE TITLE
[Build On Scroll]: 

### ISSUE THREAD

**Issue by heksa62** [scroll-tech/token-list#39]
### scrollEnvironment

alpha

### chainId

948057

### address

0x511E1Acc34C3231A0cF1aaa5F3BB75dB75018373

### name

Build On Scroll

### symbol

BOS

### decimals

18

### logoURI

https://blockscout.scroll.io/tx/0xf4dc03c3888e83f43aa5beabf6f9305e3e8e76cb6288bc79121efe861b189f4b

**Comment by yqrashawn** [comment]
Close in favor of new token list
