### ISSUE TITLE
[Zero Token]:

### ISSUE THREAD

**Issue by Lvmnvnt** [scroll-tech/token-list#41]
### scrollEnvironment

alpha

### chainId

204

### address

0x9B3cF2C734fee53c02f0778c2c4cDfF87Cc529E8

### name

Zero

### symbol

Zr0

### decimals

18

### logoURI

ipfs://QmY6jFfT2PXoma2fVDWnWhs4mJtmff7aTu2EWcowvkdQas

**Comment by yqrashawn** [comment]
Close in favor of new token list
