### ISSUE TITLE
[Token]: GXI

### ISSUE THREAD

**Issue by Alf4tta4h** [scroll-tech/token-list#52]
### scrollEnvironment

alpha

### chainId

534353

### address

0x1ceAdE83A748445B11BA03E1d51DDFCF23b3295F

### name

Galaxy Impact

### symbol

GXI

### decimals

18

### logoURI

https://ipfs.thirdwebcdn.com/ipfs/QmYb92ghGBwxn1AA7vgATzhAwXQaGBGaWM6DiBFtx5zXxi/8-3uRVkNektOC9JDa.png

**Comment by yqrashawn** [comment]
Close in favor of new token list
