### ISSUE TITLE
[Token]: SCRL

### ISSUE THREAD

**Issue by sjyim0513** [scroll-tech/token-list#65]
### scrollEnvironment

alpha

### chainId

534353

### address

0xd60342Ee53de10B013c16dE18f6d54fc8D1b1461

### name

scroller

### symbol

SCRL

### decimals

18

### logoURI

https://i.ibb.co/Vj5rDgx/ARETE-logo-3.png

**Comment by yqrashawn** [comment]
Close in favor of new token list
