### ISSUE TITLE
XOXO Token

### ISSUE THREAD

**Issue by jaguard2021** [scroll-tech/token-list#68]
### scrollEnvironment

alpha

### chainId

11155111

### address

0x530E558dB793AB55dC9e7A13061AE7f72D3E5c73

### name

XOXO

### symbol

XO

### decimals

18

### logoURI

https://indigo-cooperative-catfish-673.mypinata.cloud/ipfs/QmNxFFVQ1kmw92VepQ7QXJw5BojvhHEzTtdVU5ZGMz9cSU?_gl=1*1745qop*_ga*MTQyMjEwNjU0Mi4xNjkyNDAwMTgz*_ga_5RMPXG14TE*MTY5MjQwMjQwNy4yLjEuMTY5MjQwMzEwNi4yNy4wLjA.

**Comment by yqrashawn** [comment]
Close in favor of new token list
