### ISSUE TITLE
[Token]: DAO

### ISSUE THREAD

**Issue by Gilang26** [scroll-tech/token-list#70]
### scrollEnvironment

sepolia

### chainId

534351

### address

0x95d25Ca592B7d7fF6828A75fFF695F93199F8D8C

### name

DAO

### symbol

DAO

### decimals

9

### logoURI

https://ipfs.io/ipfs/QmRRahcmg2f5Sn8rqdiTjngV5cCHdU6pZXhquwpFhMa7JF?filename=8420.png

**Comment by yqrashawn** [comment]
Close in favor of new token list
