### ISSUE TITLE
[Token]: DCODEX21

### ISSUE THREAD

**Issue by dCodeX21** [scroll-tech/token-list#72]
### scrollEnvironment

sepolia

### chainId

534351

### address

0x0088155E26F15Bf52a289FEe8D78a09E8E723c7b

### name

dCodeX21 Scroll

### symbol

DCODEX21

### decimals

18

### logoURI

https://nftstorage.link/ipfs/bafkreidtf6klqq4n2falhzqdziiqxiiii6wfxdorkifcxayaggkm4n62fa

**Comment by dCodeX21** [comment]
L1 counterpart CA is
0x8096bef9C6dd1Fc7FBe5Ebf08c61Bd047Fb72542

**Comment by yqrashawn** [comment]
Close in favor of new token list
