### ISSUE TITLE
[Token]: HappyTokenL1

### ISSUE THREAD

**Issue by DimaKush** [scroll-tech/token-list#76]
### scrollEnvironment

sepolia

### chainId

11155111

### address

0x2D9Ac4aAaaC2286076bB86f29F5dEA30DF15991a

### name

HappyTokenL1

### symbol

HTL1

### decimals

18

### logoURI

https://ipfs.io/ipfs/QmPHH3E54KPsFf7NascWGZz8UWCREYc7QXUGHE8x5SxZms?filename=Large-logo.png

**Comment by yqrashawn** [comment]
Close in favor of new token list
